import 'package:asmaulhusna/asmaulhusna.dart';
import 'package:flutter_translate/flutter_translate.dart';

// Get all Arabic names
List<String> allArabicNames = getEveryArabicName();
List<String> allEnglishNames = getEveryEnglishName();
List<String> allNames = [
  translate('plural.allah_names_list.name_1'),
  translate('plural.allah_names_list.name_2'),
  translate('plural.allah_names_list.name_3'),
  translate('plural.allah_names_list.name_4'),
  translate('plural.allah_names_list.name_5'),
  translate('plural.allah_names_list.name_6'),
  translate('plural.allah_names_list.name_7'),
  translate('plural.allah_names_list.name_8'),
  translate('plural.allah_names_list.name_9'),
  translate('plural.allah_names_list.name_10'),
  translate('plural.allah_names_list.name_11'),
  translate('plural.allah_names_list.name_12'),
  translate('plural.allah_names_list.name_13'),
  translate('plural.allah_names_list.name_14'),
  translate('plural.allah_names_list.name_15'),
  translate('plural.allah_names_list.name_16'),
  translate('plural.allah_names_list.name_17'),
  translate('plural.allah_names_list.name_18'),
  translate('plural.allah_names_list.name_19'),
  translate('plural.allah_names_list.name_20'),
  translate('plural.allah_names_list.name_21'),
  translate('plural.allah_names_list.name_22'),
  translate('plural.allah_names_list.name_23'),
  translate('plural.allah_names_list.name_24'),
  translate('plural.allah_names_list.name_25'),
  translate('plural.allah_names_list.name_26'),
  translate('plural.allah_names_list.name_27'),
  translate('plural.allah_names_list.name_28'),
  translate('plural.allah_names_list.name_29'),
  translate('plural.allah_names_list.name_30'),
  translate('plural.allah_names_list.name_31'),
  translate('plural.allah_names_list.name_32'),
  translate('plural.allah_names_list.name_33'),
  translate('plural.allah_names_list.name_34'),
  translate('plural.allah_names_list.name_35'),
  translate('plural.allah_names_list.name_36'),
  translate('plural.allah_names_list.name_37'),
  translate('plural.allah_names_list.name_38'),
  translate('plural.allah_names_list.name_39'),
  translate('plural.allah_names_list.name_40'),
  translate('plural.allah_names_list.name_41'),
  translate('plural.allah_names_list.name_42'),
  translate('plural.allah_names_list.name_43'),
  translate('plural.allah_names_list.name_44'),
  translate('plural.allah_names_list.name_45'),
  translate('plural.allah_names_list.name_46'),
  translate('plural.allah_names_list.name_47'),
  translate('plural.allah_names_list.name_48'),
  translate('plural.allah_names_list.name_49'),
  translate('plural.allah_names_list.name_50'),
  translate('plural.allah_names_list.name_51'),
  translate('plural.allah_names_list.name_52'),
  translate('plural.allah_names_list.name_53'),
  translate('plural.allah_names_list.name_54'),
  translate('plural.allah_names_list.name_55'),
  translate('plural.allah_names_list.name_56'),
  translate('plural.allah_names_list.name_57'),
  translate('plural.allah_names_list.name_58'),
  translate('plural.allah_names_list.name_59'),
  translate('plural.allah_names_list.name_60'),
  translate('plural.allah_names_list.name_61'),
  translate('plural.allah_names_list.name_62'),
  translate('plural.allah_names_list.name_63'),
  translate('plural.allah_names_list.name_64'),
  translate('plural.allah_names_list.name_65'),
  translate('plural.allah_names_list.name_66'),
  translate('plural.allah_names_list.name_67'),
  translate('plural.allah_names_list.name_68'),
  translate('plural.allah_names_list.name_69'),
  translate('plural.allah_names_list.name_70'),
  translate('plural.allah_names_list.name_71'),
  translate('plural.allah_names_list.name_72'),
  translate('plural.allah_names_list.name_73'),
  translate('plural.allah_names_list.name_74'),
  translate('plural.allah_names_list.name_75'),
  translate('plural.allah_names_list.name_76'),
  translate('plural.allah_names_list.name_77'),
  translate('plural.allah_names_list.name_78'),
  translate('plural.allah_names_list.name_79'),
  translate('plural.allah_names_list.name_80'),
  translate('plural.allah_names_list.name_81'),
  translate('plural.allah_names_list.name_82'),
  translate('plural.allah_names_list.name_83'),
  translate('plural.allah_names_list.name_84'),
  translate('plural.allah_names_list.name_85'),
  translate('plural.allah_names_list.name_86'),
  translate('plural.allah_names_list.name_87'),
  translate('plural.allah_names_list.name_88'),
  translate('plural.allah_names_list.name_89'),
  translate('plural.allah_names_list.name_90'),
  translate('plural.allah_names_list.name_91'),
  translate('plural.allah_names_list.name_92'),
  translate('plural.allah_names_list.name_93'),
  translate('plural.allah_names_list.name_94'),
  translate('plural.allah_names_list.name_95'),
  translate('plural.allah_names_list.name_96'),
  translate('plural.allah_names_list.name_97'),
  translate('plural.allah_names_list.name_98'),
  translate('plural.allah_names_list.name_99')
];

//Define a list to hold meanings for each name
List<String> allahNamesMeaning = [
  // First 99 meanings
  translate('plural.allahNamesMeaning.Meaning 1'),
  translate('plural.allahNamesMeaning.Meaning 2'),
  translate('plural.allahNamesMeaning.Meaning 3'),
  translate('plural.allahNamesMeaning.Meaning 4'),
  translate('plural.allahNamesMeaning.Meaning 5'),
  translate('plural.allahNamesMeaning.Meaning 6'),
  translate('plural.allahNamesMeaning.Meaning 7'),
  translate('plural.allahNamesMeaning.Meaning 8'),
  translate('plural.allahNamesMeaning.Meaning 9'),
  translate('plural.allahNamesMeaning.Meaning 10'),
  translate('plural.allahNamesMeaning.Meaning 11'),
  translate('plural.allahNamesMeaning.Meaning 12'),
  translate('plural.allahNamesMeaning.Meaning 13'),
  translate('plural.allahNamesMeaning.Meaning 14'),
  translate('plural.allahNamesMeaning.Meaning 15'),
  translate('plural.allahNamesMeaning.Meaning 16'),
  translate('plural.allahNamesMeaning.Meaning 17'),
  translate('plural.allahNamesMeaning.Meaning 18'),
  translate('plural.allahNamesMeaning.Meaning 19'),
  translate('plural.allahNamesMeaning.Meaning 20'),
  translate('plural.allahNamesMeaning.Meaning 21'),
  translate('plural.allahNamesMeaning.Meaning 22'),
  translate('plural.allahNamesMeaning.Meaning 23'),
  translate('plural.allahNamesMeaning.Meaning 24'),
  translate('plural.allahNamesMeaning.Meaning 25'),
  translate('plural.allahNamesMeaning.Meaning 26'),
  translate('plural.allahNamesMeaning.Meaning 27'),
  translate('plural.allahNamesMeaning.Meaning 28'),
  translate('plural.allahNamesMeaning.Meaning 29'),
  translate('plural.allahNamesMeaning.Meaning 30'),
  translate('plural.allahNamesMeaning.Meaning 31'),
  translate('plural.allahNamesMeaning.Meaning 32'),
  translate('plural.allahNamesMeaning.Meaning 33'),
  translate('plural.allahNamesMeaning.Meaning 34'),
  translate('plural.allahNamesMeaning.Meaning 35'),
  translate('plural.allahNamesMeaning.Meaning 36'),
  translate('plural.allahNamesMeaning.Meaning 37'),
  translate('plural.allahNamesMeaning.Meaning 38'),
  translate('plural.allahNamesMeaning.Meaning 39'),
  translate('plural.allahNamesMeaning.Meaning 40'),
  translate('plural.allahNamesMeaning.Meaning 41'),
  translate('plural.allahNamesMeaning.Meaning 42'),
  translate('plural.allahNamesMeaning.Meaning 43'),
  translate('plural.allahNamesMeaning.Meaning 44'),
  translate('plural.allahNamesMeaning.Meaning 45'),
  translate('plural.allahNamesMeaning.Meaning 46'),
  translate('plural.allahNamesMeaning.Meaning 47'),
  translate('plural.allahNamesMeaning.Meaning 48'),
  translate('plural.allahNamesMeaning.Meaning 49'),
  translate('plural.allahNamesMeaning.Meaning 50'),
  translate('plural.allahNamesMeaning.Meaning 51'),
  translate('plural.allahNamesMeaning.Meaning 52'),
  translate('plural.allahNamesMeaning.Meaning 53'),
  translate('plural.allahNamesMeaning.Meaning 54'),
  translate('plural.allahNamesMeaning.Meaning 55'),
  translate('plural.allahNamesMeaning.Meaning 56'),
  translate('plural.allahNamesMeaning.Meaning 57'),
  translate('plural.allahNamesMeaning.Meaning 58'),
  translate('plural.allahNamesMeaning.Meaning 59'),
  translate('plural.allahNamesMeaning.Meaning 60'),
  translate('plural.allahNamesMeaning.Meaning 61'),
  translate('plural.allahNamesMeaning.Meaning 62'),
  translate('plural.allahNamesMeaning.Meaning 63'),
  translate('plural.allahNamesMeaning.Meaning 64'),
  translate('plural.allahNamesMeaning.Meaning 65'),
  translate('plural.allahNamesMeaning.Meaning 66'),
  translate('plural.allahNamesMeaning.Meaning 67'),
  translate('plural.allahNamesMeaning.Meaning 68'),
  translate('plural.allahNamesMeaning.Meaning 69'),
  translate('plural.allahNamesMeaning.Meaning 70'),
  translate('plural.allahNamesMeaning.Meaning 71'),
  translate('plural.allahNamesMeaning.Meaning 72'),
  translate('plural.allahNamesMeaning.Meaning 73'),
  translate('plural.allahNamesMeaning.Meaning 74'),
  translate('plural.allahNamesMeaning.Meaning 75'),
  translate('plural.allahNamesMeaning.Meaning 76'),
  translate('plural.allahNamesMeaning.Meaning 77'),
  translate('plural.allahNamesMeaning.Meaning 78'),
  translate('plural.allahNamesMeaning.Meaning 79'),
  translate('plural.allahNamesMeaning.Meaning 80'),
  translate('plural.allahNamesMeaning.Meaning 81'),
  translate('plural.allahNamesMeaning.Meaning 82'),
  translate('plural.allahNamesMeaning.Meaning 83'),
  translate('plural.allahNamesMeaning.Meaning 84'),
  translate('plural.allahNamesMeaning.Meaning 85'),
  translate('plural.allahNamesMeaning.Meaning 86'),
  translate('plural.allahNamesMeaning.Meaning 87'),
  translate('plural.allahNamesMeaning.Meaning 88'),
  translate('plural.allahNamesMeaning.Meaning 89'),
  translate('plural.allahNamesMeaning.Meaning 89'),
  translate('plural.allahNamesMeaning.Meaning 90'),
  translate('plural.allahNamesMeaning.Meaning 91'),
  translate('plural.allahNamesMeaning.Meaning 92'),
  translate('plural.allahNamesMeaning.Meaning 93'),
  translate('plural.allahNamesMeaning.Meaning 94'),
  translate('plural.allahNamesMeaning.Meaning 95'),
  translate('plural.allahNamesMeaning.Meaning 96'),
  translate('plural.allahNamesMeaning.Meaning 97'),
  translate('plural.allahNamesMeaning.Meaning 98'),
  translate('plural.allahNamesMeaning.Meaning 99'),
];
